name = "cf-mail0"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cf_mail_db"
database_id = "017a6b09-3cb7-4d20-96cd-97f2b525c98d"

[[r2_buckets]]
binding = "R2"
bucket_name = "cf-mail-storage"

[vars]
ADMIN_PASSWORD = "Whd841725"

[assets]
directory = "public"
